# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: "ubuntu-latest"

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: "JaCoCo"
    summaryFileLocation: "$(System.DefaultWorkingDirectory)/**/site/jacoco/jacoco.xml"
    reportDirectory: "$(System.DefaultWorkingDirectory)/**/site/jacoco"
    failIfCoverageEmpty: true

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |    
      Write-Host "The Deployment Request ID is: $env:Release_ReleaseId"  
      $url = "https://prod-111.westus.logic.azure.com:443/workflows/8e48f1c51e04474592e302bd2a423426/triggers/manual/paths/invoke?api-version=2016-06-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=Hc49eJSIN10FXdvVPXuyVCb0bueNl5U4aFgiQUygCck"
      $method = "POST"
      $body = @{
        StepName = "Deploy"
        LogType = "Info"
        LogText = "Deploy starting"
        DeployRequestId = "$env:Release_ReleaseId"
      }

      $headers = @{
        "Content-Type" = "application/json"
      }

      $response = Invoke-RestMethod -Uri $url -Method $method -Body (ConvertTo-Json $body) -Headers $headers

      Write-Output $response